// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command.proto

package axon_server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// An instruction from the components that provides the Command Handler towards AxonServer.
type CommandProviderOutbound struct {
	// The instruction for AxonServer
	//
	// Types that are valid to be assigned to Request:
	//	*CommandProviderOutbound_Subscribe
	//	*CommandProviderOutbound_Unsubscribe
	//	*CommandProviderOutbound_FlowControl
	//	*CommandProviderOutbound_CommandResponse
	//	*CommandProviderOutbound_Ack
	Request isCommandProviderOutbound_Request `protobuf_oneof:"request"`
	// Instruction identifier. If this identifier is set, this instruction will be acknowledged via inbound stream
	InstructionId        string   `protobuf:"bytes,6,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandProviderOutbound) Reset()         { *m = CommandProviderOutbound{} }
func (m *CommandProviderOutbound) String() string { return proto.CompactTextString(m) }
func (*CommandProviderOutbound) ProtoMessage()    {}
func (*CommandProviderOutbound) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{0}
}

func (m *CommandProviderOutbound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandProviderOutbound.Unmarshal(m, b)
}
func (m *CommandProviderOutbound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandProviderOutbound.Marshal(b, m, deterministic)
}
func (m *CommandProviderOutbound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandProviderOutbound.Merge(m, src)
}
func (m *CommandProviderOutbound) XXX_Size() int {
	return xxx_messageInfo_CommandProviderOutbound.Size(m)
}
func (m *CommandProviderOutbound) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandProviderOutbound.DiscardUnknown(m)
}

var xxx_messageInfo_CommandProviderOutbound proto.InternalMessageInfo

type isCommandProviderOutbound_Request interface {
	isCommandProviderOutbound_Request()
}

type CommandProviderOutbound_Subscribe struct {
	Subscribe *CommandSubscription `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type CommandProviderOutbound_Unsubscribe struct {
	Unsubscribe *CommandSubscription `protobuf:"bytes,2,opt,name=unsubscribe,proto3,oneof"`
}

type CommandProviderOutbound_FlowControl struct {
	FlowControl *FlowControl `protobuf:"bytes,3,opt,name=flow_control,json=flowControl,proto3,oneof"`
}

type CommandProviderOutbound_CommandResponse struct {
	CommandResponse *CommandResponse `protobuf:"bytes,4,opt,name=command_response,json=commandResponse,proto3,oneof"`
}

type CommandProviderOutbound_Ack struct {
	Ack *InstructionAck `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

func (*CommandProviderOutbound_Subscribe) isCommandProviderOutbound_Request() {}

func (*CommandProviderOutbound_Unsubscribe) isCommandProviderOutbound_Request() {}

func (*CommandProviderOutbound_FlowControl) isCommandProviderOutbound_Request() {}

func (*CommandProviderOutbound_CommandResponse) isCommandProviderOutbound_Request() {}

func (*CommandProviderOutbound_Ack) isCommandProviderOutbound_Request() {}

func (m *CommandProviderOutbound) GetRequest() isCommandProviderOutbound_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *CommandProviderOutbound) GetSubscribe() *CommandSubscription {
	if x, ok := m.GetRequest().(*CommandProviderOutbound_Subscribe); ok {
		return x.Subscribe
	}
	return nil
}

func (m *CommandProviderOutbound) GetUnsubscribe() *CommandSubscription {
	if x, ok := m.GetRequest().(*CommandProviderOutbound_Unsubscribe); ok {
		return x.Unsubscribe
	}
	return nil
}

func (m *CommandProviderOutbound) GetFlowControl() *FlowControl {
	if x, ok := m.GetRequest().(*CommandProviderOutbound_FlowControl); ok {
		return x.FlowControl
	}
	return nil
}

func (m *CommandProviderOutbound) GetCommandResponse() *CommandResponse {
	if x, ok := m.GetRequest().(*CommandProviderOutbound_CommandResponse); ok {
		return x.CommandResponse
	}
	return nil
}

func (m *CommandProviderOutbound) GetAck() *InstructionAck {
	if x, ok := m.GetRequest().(*CommandProviderOutbound_Ack); ok {
		return x.Ack
	}
	return nil
}

func (m *CommandProviderOutbound) GetInstructionId() string {
	if m != nil {
		return m.InstructionId
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CommandProviderOutbound) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CommandProviderOutbound_Subscribe)(nil),
		(*CommandProviderOutbound_Unsubscribe)(nil),
		(*CommandProviderOutbound_FlowControl)(nil),
		(*CommandProviderOutbound_CommandResponse)(nil),
		(*CommandProviderOutbound_Ack)(nil),
	}
}

// An instruction or confirmation from AxonServer towards the component that provides the Command Handler
type CommandProviderInbound struct {
	// The instruction from AxonServer for this component
	//
	// Types that are valid to be assigned to Request:
	//	*CommandProviderInbound_Ack
	//	*CommandProviderInbound_Command
	Request isCommandProviderInbound_Request `protobuf_oneof:"request"`
	// Instruction identifier. If this identifier is set, this instruction will be acknowledged via outbound stream
	InstructionId        string   `protobuf:"bytes,3,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandProviderInbound) Reset()         { *m = CommandProviderInbound{} }
func (m *CommandProviderInbound) String() string { return proto.CompactTextString(m) }
func (*CommandProviderInbound) ProtoMessage()    {}
func (*CommandProviderInbound) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{1}
}

func (m *CommandProviderInbound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandProviderInbound.Unmarshal(m, b)
}
func (m *CommandProviderInbound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandProviderInbound.Marshal(b, m, deterministic)
}
func (m *CommandProviderInbound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandProviderInbound.Merge(m, src)
}
func (m *CommandProviderInbound) XXX_Size() int {
	return xxx_messageInfo_CommandProviderInbound.Size(m)
}
func (m *CommandProviderInbound) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandProviderInbound.DiscardUnknown(m)
}

var xxx_messageInfo_CommandProviderInbound proto.InternalMessageInfo

type isCommandProviderInbound_Request interface {
	isCommandProviderInbound_Request()
}

type CommandProviderInbound_Ack struct {
	Ack *InstructionAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type CommandProviderInbound_Command struct {
	Command *Command `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

func (*CommandProviderInbound_Ack) isCommandProviderInbound_Request() {}

func (*CommandProviderInbound_Command) isCommandProviderInbound_Request() {}

func (m *CommandProviderInbound) GetRequest() isCommandProviderInbound_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *CommandProviderInbound) GetAck() *InstructionAck {
	if x, ok := m.GetRequest().(*CommandProviderInbound_Ack); ok {
		return x.Ack
	}
	return nil
}

func (m *CommandProviderInbound) GetCommand() *Command {
	if x, ok := m.GetRequest().(*CommandProviderInbound_Command); ok {
		return x.Command
	}
	return nil
}

func (m *CommandProviderInbound) GetInstructionId() string {
	if m != nil {
		return m.InstructionId
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CommandProviderInbound) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CommandProviderInbound_Ack)(nil),
		(*CommandProviderInbound_Command)(nil),
	}
}

// A message representing a Command that needs to be routed to a component capable of handling it
type Command struct {
	// The unique identifier of the Command Message
	MessageIdentifier string `protobuf:"bytes,1,opt,name=message_identifier,json=messageIdentifier,proto3" json:"message_identifier,omitempty"`
	// The name of the command, used for routing it to a destination capable of handling it
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The time at which the command was dispatched
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The payload of the Command, providing details on the instructions for the recipient
	Payload *SerializedObject `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// Meta Data entries of the Command Message, providing contextual information to the recipient
	MetaData map[string]*MetaDataValue `protobuf:"bytes,5,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Instructions for AxonServer when routing this Command Message
	ProcessingInstructions []*ProcessingInstruction `protobuf:"bytes,6,rep,name=processing_instructions,json=processingInstructions,proto3" json:"processing_instructions,omitempty"`
	// The unique identifier of the component dispatching this message
	ClientId string `protobuf:"bytes,7,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The name/type of the component dispatching this message
	ComponentName        string   `protobuf:"bytes,8,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{2}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetMessageIdentifier() string {
	if m != nil {
		return m.MessageIdentifier
	}
	return ""
}

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Command) GetPayload() *SerializedObject {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Command) GetMetaData() map[string]*MetaDataValue {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *Command) GetProcessingInstructions() []*ProcessingInstruction {
	if m != nil {
		return m.ProcessingInstructions
	}
	return nil
}

func (m *Command) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Command) GetComponentName() string {
	if m != nil {
		return m.ComponentName
	}
	return ""
}

// Message representing the result of Command Handler execution
type CommandResponse struct {
	// The unique identifier of the response message
	MessageIdentifier string `protobuf:"bytes,1,opt,name=message_identifier,json=messageIdentifier,proto3" json:"message_identifier,omitempty"`
	// An error code describing the error, if any
	ErrorCode string `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// A detailed description of the error
	ErrorMessage *ErrorMessage `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// The payload to provide as a result to the dispatcher
	Payload *SerializedObject `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// Any meta data entries providing contextual information back to the dispatcher
	MetaData map[string]*MetaDataValue `protobuf:"bytes,5,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Instructions for AxonServer when routing this Command Response Message
	ProcessingInstructions []*ProcessingInstruction `protobuf:"bytes,6,rep,name=processing_instructions,json=processingInstructions,proto3" json:"processing_instructions,omitempty"`
	// The unique identifier of the Command Message for which this is the response
	RequestIdentifier    string   `protobuf:"bytes,7,opt,name=request_identifier,json=requestIdentifier,proto3" json:"request_identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandResponse) Reset()         { *m = CommandResponse{} }
func (m *CommandResponse) String() string { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()    {}
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{3}
}

func (m *CommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandResponse.Unmarshal(m, b)
}
func (m *CommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandResponse.Marshal(b, m, deterministic)
}
func (m *CommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandResponse.Merge(m, src)
}
func (m *CommandResponse) XXX_Size() int {
	return xxx_messageInfo_CommandResponse.Size(m)
}
func (m *CommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandResponse proto.InternalMessageInfo

func (m *CommandResponse) GetMessageIdentifier() string {
	if m != nil {
		return m.MessageIdentifier
	}
	return ""
}

func (m *CommandResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *CommandResponse) GetErrorMessage() *ErrorMessage {
	if m != nil {
		return m.ErrorMessage
	}
	return nil
}

func (m *CommandResponse) GetPayload() *SerializedObject {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *CommandResponse) GetMetaData() map[string]*MetaDataValue {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *CommandResponse) GetProcessingInstructions() []*ProcessingInstruction {
	if m != nil {
		return m.ProcessingInstructions
	}
	return nil
}

func (m *CommandResponse) GetRequestIdentifier() string {
	if m != nil {
		return m.RequestIdentifier
	}
	return ""
}

// Message describing a component's capability of handling a command type
type CommandSubscription struct {
	// A unique identifier for this subscription. This identifier is returned in Acknowledgements to allow
	//pipelining of subscription messages
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// The name of the command the component can handle
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// The name/type of the component handling the command
	ComponentName string `protobuf:"bytes,3,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	// The unique identifier of the component instance subscribing
	ClientId string `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// A number that represents the client's relative load capacity compared to other clients.
	//This information is interpreted by Axon Server in relation to the other connected nodes' values.
	//Used to balance the dispatching of commands. If set to 0, Axon Server consider 100 as default value.
	LoadFactor           int32    `protobuf:"varint,5,opt,name=load_factor,json=loadFactor,proto3" json:"load_factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandSubscription) Reset()         { *m = CommandSubscription{} }
func (m *CommandSubscription) String() string { return proto.CompactTextString(m) }
func (*CommandSubscription) ProtoMessage()    {}
func (*CommandSubscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{4}
}

func (m *CommandSubscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSubscription.Unmarshal(m, b)
}
func (m *CommandSubscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSubscription.Marshal(b, m, deterministic)
}
func (m *CommandSubscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSubscription.Merge(m, src)
}
func (m *CommandSubscription) XXX_Size() int {
	return xxx_messageInfo_CommandSubscription.Size(m)
}
func (m *CommandSubscription) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSubscription.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSubscription proto.InternalMessageInfo

func (m *CommandSubscription) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *CommandSubscription) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *CommandSubscription) GetComponentName() string {
	if m != nil {
		return m.ComponentName
	}
	return ""
}

func (m *CommandSubscription) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *CommandSubscription) GetLoadFactor() int32 {
	if m != nil {
		return m.LoadFactor
	}
	return 0
}

func init() {
	proto.RegisterType((*CommandProviderOutbound)(nil), "io.axoniq.axonserver.grpc.command.CommandProviderOutbound")
	proto.RegisterType((*CommandProviderInbound)(nil), "io.axoniq.axonserver.grpc.command.CommandProviderInbound")
	proto.RegisterType((*Command)(nil), "io.axoniq.axonserver.grpc.command.Command")
	proto.RegisterMapType((map[string]*MetaDataValue)(nil), "io.axoniq.axonserver.grpc.command.Command.MetaDataEntry")
	proto.RegisterType((*CommandResponse)(nil), "io.axoniq.axonserver.grpc.command.CommandResponse")
	proto.RegisterMapType((map[string]*MetaDataValue)(nil), "io.axoniq.axonserver.grpc.command.CommandResponse.MetaDataEntry")
	proto.RegisterType((*CommandSubscription)(nil), "io.axoniq.axonserver.grpc.command.CommandSubscription")
}

func init() {
	proto.RegisterFile("command.proto", fileDescriptor_213c0bb044472049)
}

var fileDescriptor_213c0bb044472049 = []byte{
	// 783 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xfd, 0x6e, 0xe3, 0x44,
	0x10, 0x8f, 0xeb, 0xa4, 0x89, 0x27, 0x4d, 0x3f, 0x16, 0xa9, 0xb5, 0x42, 0x11, 0x25, 0x12, 0x10,
	0x40, 0x4d, 0xab, 0x20, 0xa1, 0x52, 0x09, 0x04, 0xfd, 0x52, 0x22, 0x28, 0xad, 0x5c, 0xd1, 0x3f,
	0x2a, 0x21, 0x6b, 0xb3, 0xde, 0x84, 0x25, 0xf6, 0xae, 0xbb, 0xde, 0xa4, 0x94, 0x37, 0x80, 0x87,
	0xe0, 0x25, 0x78, 0x12, 0xa4, 0x7b, 0x8c, 0x7b, 0x88, 0x93, 0xed, 0xcd, 0xe7, 0x45, 0x69, 0xd2,
	0x3b, 0x9d, 0xee, 0xaf, 0x78, 0x67, 0xf6, 0xf7, 0x9b, 0x99, 0x9d, 0xdf, 0xec, 0x06, 0x4a, 0x44,
	0x04, 0x01, 0xe6, 0x5e, 0x2d, 0x94, 0x42, 0x09, 0xf4, 0x09, 0x13, 0x35, 0xfc, 0xa7, 0xe0, 0xec,
	0x3e, 0xf9, 0x89, 0xa8, 0xec, 0x53, 0x59, 0xeb, 0xc8, 0x90, 0xd4, 0xf4, 0xc6, 0xf2, 0x5a, 0xfc,
	0x21, 0x78, 0x0a, 0xa8, 0xbc, 0x34, 0x61, 0xe7, 0x34, 0xf5, 0x5c, 0x4b, 0xd1, 0x67, 0x1e, 0x95,
	0x57, 0x3d, 0xd5, 0x12, 0x3d, 0xee, 0xa1, 0x5b, 0xb0, 0xa2, 0x5e, 0x2b, 0x22, 0x92, 0xb5, 0xa8,
	0x6d, 0xec, 0x19, 0xd5, 0x62, 0xfd, 0x9b, 0xda, 0x93, 0x01, 0x6a, 0x9a, 0xee, 0x26, 0x85, 0x86,
	0x8a, 0x09, 0xde, 0xc8, 0x38, 0x23, 0x2a, 0x74, 0x07, 0xc5, 0x1e, 0x1f, 0x31, 0xaf, 0xbc, 0x21,
	0xf3, 0x38, 0x19, 0xfa, 0x09, 0xd6, 0xda, 0xbe, 0x78, 0x70, 0x89, 0xe0, 0x4a, 0x0a, 0xdf, 0x36,
	0x13, 0xf2, 0xcf, 0xe6, 0x90, 0x5f, 0xf8, 0xe2, 0xe1, 0x34, 0xdd, 0x1d, 0x93, 0xb5, 0x47, 0x4b,
	0xe4, 0xc2, 0xa6, 0x0e, 0xed, 0x4a, 0x1a, 0x85, 0x31, 0xce, 0xce, 0x26, 0x84, 0xf5, 0xc5, 0xb3,
	0x75, 0x34, 0xb2, 0x91, 0x71, 0x36, 0xc8, 0xa4, 0x09, 0x7d, 0x07, 0x26, 0x26, 0x5d, 0x3b, 0x97,
	0x70, 0x7e, 0x31, 0x87, 0xb3, 0xc9, 0x23, 0x25, 0x7b, 0x24, 0xae, 0xf8, 0x47, 0xd2, 0x6d, 0x64,
	0x9c, 0x18, 0x87, 0x3e, 0x85, 0x75, 0x36, 0x72, 0xb8, 0xcc, 0xb3, 0x57, 0xf7, 0x8c, 0xaa, 0xe5,
	0x94, 0xc6, 0xac, 0x4d, 0xef, 0xc4, 0x82, 0xbc, 0xa4, 0xf7, 0x3d, 0x1a, 0xa9, 0xca, 0xff, 0x06,
	0x6c, 0x4f, 0xb5, 0xbb, 0xc9, 0xd3, 0x6e, 0xeb, 0x5c, 0x8c, 0x67, 0xe6, 0x72, 0x01, 0x79, 0x5d,
	0x9d, 0x6e, 0xe8, 0x97, 0x8b, 0x1f, 0x51, 0x23, 0xe3, 0x0c, 0xc0, 0x33, 0x6a, 0x32, 0x9f, 0xa8,
	0xe9, 0xdf, 0x2c, 0xe4, 0x35, 0x11, 0xda, 0x07, 0x14, 0xd0, 0x28, 0xc2, 0x1d, 0xea, 0x32, 0x8f,
	0x72, 0xc5, 0xda, 0x8c, 0xca, 0xa4, 0x26, 0xcb, 0xd9, 0xd2, 0x9e, 0xe6, 0xd0, 0x81, 0x10, 0x64,
	0x39, 0x0e, 0x52, 0x09, 0x5a, 0x4e, 0xf2, 0x8d, 0x76, 0xc1, 0x52, 0x2c, 0xa0, 0x91, 0xc2, 0x41,
	0x98, 0xc4, 0x36, 0x9d, 0x91, 0x01, 0x9d, 0x43, 0x3e, 0xc4, 0x8f, 0xbe, 0xc0, 0x9e, 0x56, 0xc2,
	0x57, 0x73, 0xca, 0xbc, 0xa1, 0x92, 0x61, 0x9f, 0xfd, 0x45, 0xbd, 0xab, 0xd6, 0x1f, 0x94, 0x28,
	0x67, 0x80, 0x45, 0xbf, 0x82, 0x15, 0x50, 0x85, 0x5d, 0x0f, 0x2b, 0x6c, 0xe7, 0xf6, 0xcc, 0x6a,
	0xb1, 0x7e, 0xb4, 0xf8, 0x79, 0xd5, 0x2e, 0xa9, 0xc2, 0x67, 0x58, 0xe1, 0x73, 0xae, 0xe4, 0xa3,
	0x53, 0x08, 0xf4, 0x12, 0x31, 0xd8, 0x09, 0xa5, 0x20, 0x34, 0x8a, 0x18, 0xef, 0xb8, 0x63, 0x27,
	0x16, 0xd9, 0xab, 0x49, 0x90, 0xc3, 0x39, 0x41, 0xae, 0x87, 0xc8, 0xb1, 0x0e, 0x3b, 0xdb, 0xe1,
	0x2c, 0x73, 0x84, 0x3e, 0x04, 0x8b, 0xf8, 0x8c, 0x72, 0x15, 0xb7, 0x28, 0x9f, 0x9c, 0x5f, 0x21,
	0x35, 0x34, 0x93, 0x26, 0x12, 0x11, 0x84, 0x82, 0xc7, 0xfe, 0xe4, 0x84, 0x0b, 0x69, 0x13, 0x87,
	0xd6, 0x5f, 0x70, 0x40, 0xcb, 0x14, 0x4a, 0x13, 0x95, 0xa0, 0x4d, 0x30, 0xbb, 0xf4, 0x51, 0xf7,
	0x2b, 0xfe, 0x44, 0xdf, 0x43, 0xae, 0x8f, 0xfd, 0xde, 0xe0, 0x96, 0xa8, 0xce, 0xc9, 0x7f, 0x40,
	0x75, 0x1b, 0xef, 0x77, 0x52, 0xd8, 0xf1, 0xca, 0x91, 0x51, 0x79, 0x91, 0x85, 0x8d, 0xa9, 0x61,
	0x5c, 0x56, 0x28, 0x1f, 0x01, 0x50, 0x29, 0x85, 0x74, 0x89, 0xf0, 0x06, 0x72, 0xb1, 0x12, 0xcb,
	0xa9, 0xf0, 0x28, 0xfa, 0x19, 0x4a, 0xa9, 0x5b, 0x23, 0xf5, 0xb5, 0xf3, 0xf9, 0x9c, 0x6c, 0xcf,
	0xe3, 0xfd, 0x97, 0xe9, 0x76, 0x67, 0x8d, 0x8e, 0xad, 0xde, 0x96, 0xc6, 0x7e, 0x7b, 0x5d, 0x63,
	0x3f, 0x2c, 0x7f, 0x6d, 0xbd, 0x0f, 0x5a, 0xdb, 0x07, 0xa4, 0x87, 0x7d, 0xbc, 0x59, 0xa9, 0xe8,
	0xb6, 0xb4, 0x67, 0xd4, 0xac, 0x77, 0x25, 0xab, 0xff, 0x0c, 0xf8, 0x60, 0xc6, 0x8b, 0x14, 0x6b,
	0x65, 0x24, 0x2d, 0x1d, 0xd4, 0x1a, 0x4a, 0x0a, 0xd9, 0x93, 0x17, 0xa5, 0x35, 0x71, 0xf5, 0x4d,
	0x4d, 0x8d, 0x39, 0x63, 0x6a, 0x26, 0x27, 0x2f, 0x3b, 0x35, 0x79, 0x1f, 0x43, 0x31, 0x6e, 0xbe,
	0xdb, 0xc6, 0x44, 0x09, 0x99, 0xbc, 0x2c, 0x39, 0x07, 0x62, 0xd3, 0x45, 0x62, 0xa9, 0xff, 0xb3,
	0x02, 0xeb, 0x83, 0xac, 0xa9, 0xec, 0x33, 0x42, 0xd1, 0xdf, 0x06, 0xc0, 0x55, 0x48, 0xf9, 0x8d,
	0x92, 0x14, 0x07, 0xe8, 0x78, 0x71, 0x91, 0x4c, 0xff, 0x65, 0x28, 0x7f, 0xbb, 0x3c, 0x56, 0xbf,
	0x3f, 0x95, 0x4c, 0xd5, 0x38, 0x34, 0x90, 0x0f, 0x85, 0x33, 0x16, 0x85, 0x58, 0x91, 0xdf, 0xd1,
	0x12, 0x2f, 0x48, 0xf9, 0x19, 0x0f, 0x72, 0x25, 0x73, 0xb2, 0x7b, 0x6d, 0xdc, 0xd9, 0x91, 0x24,
	0x07, 0x61, 0xb7, 0x73, 0x10, 0xef, 0x3d, 0x88, 0xb1, 0x6e, 0x0a, 0x6e, 0xad, 0x26, 0x7f, 0x91,
	0xbe, 0x7e, 0x15, 0x00, 0x00, 0xff, 0xff, 0x13, 0x99, 0xa0, 0x71, 0x64, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommandServiceClient is the client API for CommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommandServiceClient interface {
	// Opens a stream allowing clients to register command handlers and receive commands.
	OpenStream(ctx context.Context, opts ...grpc.CallOption) (CommandService_OpenStreamClient, error)
	// Dispatches the given command, returning the result of command execution
	Dispatch(ctx context.Context, in *Command, opts ...grpc.CallOption) (*CommandResponse, error)
}

type commandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandServiceClient(cc grpc.ClientConnInterface) CommandServiceClient {
	return &commandServiceClient{cc}
}

func (c *commandServiceClient) OpenStream(ctx context.Context, opts ...grpc.CallOption) (CommandService_OpenStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CommandService_serviceDesc.Streams[0], "/io.axoniq.axonserver.grpc.command.CommandService/OpenStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &commandServiceOpenStreamClient{stream}
	return x, nil
}

type CommandService_OpenStreamClient interface {
	Send(*CommandProviderOutbound) error
	Recv() (*CommandProviderInbound, error)
	grpc.ClientStream
}

type commandServiceOpenStreamClient struct {
	grpc.ClientStream
}

func (x *commandServiceOpenStreamClient) Send(m *CommandProviderOutbound) error {
	return x.ClientStream.SendMsg(m)
}

func (x *commandServiceOpenStreamClient) Recv() (*CommandProviderInbound, error) {
	m := new(CommandProviderInbound)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *commandServiceClient) Dispatch(ctx context.Context, in *Command, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, "/io.axoniq.axonserver.grpc.command.CommandService/Dispatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandServiceServer is the server API for CommandService service.
type CommandServiceServer interface {
	// Opens a stream allowing clients to register command handlers and receive commands.
	OpenStream(CommandService_OpenStreamServer) error
	// Dispatches the given command, returning the result of command execution
	Dispatch(context.Context, *Command) (*CommandResponse, error)
}

// UnimplementedCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommandServiceServer struct {
}

func (*UnimplementedCommandServiceServer) OpenStream(srv CommandService_OpenStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method OpenStream not implemented")
}
func (*UnimplementedCommandServiceServer) Dispatch(ctx context.Context, req *Command) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dispatch not implemented")
}

func RegisterCommandServiceServer(s *grpc.Server, srv CommandServiceServer) {
	s.RegisterService(&_CommandService_serviceDesc, srv)
}

func _CommandService_OpenStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommandServiceServer).OpenStream(&commandServiceOpenStreamServer{stream})
}

type CommandService_OpenStreamServer interface {
	Send(*CommandProviderInbound) error
	Recv() (*CommandProviderOutbound, error)
	grpc.ServerStream
}

type commandServiceOpenStreamServer struct {
	grpc.ServerStream
}

func (x *commandServiceOpenStreamServer) Send(m *CommandProviderInbound) error {
	return x.ServerStream.SendMsg(m)
}

func (x *commandServiceOpenStreamServer) Recv() (*CommandProviderOutbound, error) {
	m := new(CommandProviderOutbound)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CommandService_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.axoniq.axonserver.grpc.command.CommandService/Dispatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).Dispatch(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.axoniq.axonserver.grpc.command.CommandService",
	HandlerType: (*CommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dispatch",
			Handler:    _CommandService_Dispatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenStream",
			Handler:       _CommandService_OpenStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "command.proto",
}
